#!/system/bin/sh

umask 077
RUNDIR=${0%/*}
[ "$RUNDIR" != "$0" ] || RUNDIR=.
RUNDIR="$(cd "$RUNDIR" && pwd)" || exit 1

if [ -f "$RUNDIR/classes.dex" ]; then
    CLASSPATH="$RUNDIR/classes.dex"
elif [ -f "$RUNDIR/service.apk" ]; then
    CLASSPATH="$RUNDIR/service.apk"
else
    exit 1
fi

exec /system/bin/app_process -Djava.class.path="$CLASSPATH" "$RUNDIR" --nice-name=TEESimulator org.matrix.TEESimulator.App
