#!/system/bin/sh

umask 077
MODDIR=$1
export RUST_LOG=off

if [ -f "$MODDIR/classes.dex" ]; then
    CLASSPATH="$MODDIR/classes.dex"
elif [ -f "$MODDIR/service.apk" ]; then
    CLASSPATH="$MODDIR/service.apk"
else
    exit 1
fi

exec /system/bin/app_process -Djava.class.path="$CLASSPATH" "$MODDIR" --nice-name=TEESimulator org.matrix.TEESimulator.App
