[target.aarch64-linux-android]
linker = "C:\\Users\\Seva\\AppData\\Local\\Android\\Sdk\\ndk\\magisk\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android23-clang.cmd"

[target.thumbv7neon-linux-androideabi]
linker = "C:\\Users\\Seva\\AppData\\Local\\Android\\Sdk\\ndk\\magisk\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi23-clang.cmd"

[build]
target-dir = "../out/rust"
rustflags = ["-Z", "unstable-options"]

[unstable]
build-std = ["std", "panic_abort"]
