#![allow(dead_code)]
use base::const_format::concatcp;

#[path = "../../out/generated/flags.rs"]
mod flags;

pub const POST_FS_DATA_WAIT_TIME: i32 = 40;
pub const APPLET_NAMES: &[&str] = &["su", "resetprop"];

// versions
pub use flags::*;
pub const MAGISK_FULL_VER: &str = concatcp!(MAGISK_VERSION, "(", MAGISK_VER_CODE, ")");

pub const APP_PACKAGE_NAME: &str = "com.topjohnwu.magisk";

// data paths
pub const SECURE_DIR: &str = "/data/adb";
pub const MODULEROOT: &str = concatcp!(SECURE_DIR, "/modules");
pub const MODULEUPGRADE: &str = concatcp!(SECURE_DIR, "/modules_update");
pub const DATABIN: &str = concatcp!(SECURE_DIR, "/ms");
pub const MAGISKDB: &str = concatcp!(SECURE_DIR, "/ms.db");

// tmpfs paths
pub const INTERNAL_DIR: &str = ".ms";
pub const MAIN_CONFIG: &str = concatcp!(INTERNAL_DIR, "/config");
pub const PREINITMIRR: &str = concatcp!(INTERNAL_DIR, "/preinit");
pub const MODULEMNT: &str = concatcp!(INTERNAL_DIR, "/modules");
pub const WORKERDIR: &str = concatcp!(INTERNAL_DIR, "/worker");
pub const BBPATH: &str = concatcp!(INTERNAL_DIR, "/busybox");
pub const DEVICEDIR: &str = concatcp!(INTERNAL_DIR, "/device");
pub const MAIN_SOCKET: &str = concatcp!(DEVICEDIR, "/socket");
pub const PREINITDEV: &str = concatcp!(DEVICEDIR, "/preinit");
pub const ROOTOVL: &str = concatcp!(INTERNAL_DIR, "/rootdir");
pub const ROOTMNT: &str = concatcp!(ROOTOVL, "/.mount_list");
pub const SELINUXMOCK: &str = concatcp!(INTERNAL_DIR, "/selinux");

// Per-build identifiers generated by build.py (BUILD_ID is a random 5-char lowercase string)
pub const MAIN_BIN_NAME: &str = BUILD_ID;
pub const MAIN_BIN_NAME_32: &str = concatcp!(BUILD_ID, "32");
pub const POLICY_BIN_NAME: &str = concatcp!(BUILD_ID, "p");
pub const DAEMON_PROC_NAME: &str = concatcp!(BUILD_ID, "d");
// Worker tmpfs source label (must match revert_unmount check in mount.rs)
pub const WORKER_SOURCE: &str = BUILD_ID;

// Stable ramdisk filename (not randomized - not accessible to apps at runtime)
pub const RAMDISK_BIN_NAME: &str = "ms";
// Backup config path in ramdisk (must match boot_patch.sh)
pub const BACKUP_CONFIG: &str = ".backup/.cfg";

// Unconstrained domain the daemon and root processes run in
pub const SEPOL_PROC_DOMAIN: &str = "ms";
pub const MAGISK_PROC_CON: &str = concatcp!("u:r:", SEPOL_PROC_DOMAIN, ":s0");
// Unconstrained file type that anyone can access
pub const SEPOL_FILE_TYPE: &str = "ms_file";
pub const MAGISK_FILE_CON: &str = concatcp!("u:object_r:", SEPOL_FILE_TYPE, ":s0");
